### ISSUE TITLE
Resize images to match magnification/dpi.

### ISSUE THREAD

**Issue by iandobbie** [will-moore/figure#34]
I have 3 data sets that I wish to compare, they are from different systems with different pixel sizes. I am able to label them all with scales bars (of the right scale!) and have the same viewport size is pixels (eg 200x200) , al of this is brilliant. My question is can I make them all have the same effective magnification. eg the one with 10 nm pixels needs to be 4 times smaller than the one with 40 nm pixels. 

Thanks, Ian

**Comment by will-moore** [comment]
I've opened a PR with this functionality: https://github.com/will-moore/figure/pull/43
