### ISSUE TITLE
Change colors of channels

### ISSUE THREAD

**Issue by Trefex** [will-moore/figure#36]
Some users wanted to change the color of the channels.

The pre-defined colors are the standard but offer very little flexibility in terms of coloring.

Perhaps a color picker like in OMERO view figure could be used?

**Comment by will-moore** [comment]
Hi @Trefex - Do you think this color-picker would be suitable for OMERO.figure: http://mjolnic.com/bootstrap-colorpicker/
Just wondering if it's easy enough to find the color you want (it is quite small).

**Comment by Trefex** [comment]
Hi @will-moore This seems perfect. And it that form raises a bunch of practical next questions. 

How can I get the same color in the next label ? Possibility to save or enter my own HEX code? Save the chosen color throughout all figures with up to max. 5 or 10 saved colors? 

The simple fact of choosing the right color with this picker is fairly nice and smooth with the mentioned plugin though!

**Comment by will-moore** [comment]
Hi @Trefex. I think I can add any picked colours to a global "palate" of user's colours so if you pick a new colour for a channel then go to edit labels, your chosen colour is already available (for that figure). I can also make it possible to copy and paste HEX colours.
I'm thinking that the colour-picker "More colours..." option can be added below the standard colours in the current colour drop-down menu, a bit like in Powerpoint. And that would open the colour-picker dialog.
It's a bit harder to decide if/how I want to have saved colours across all your figures. A lot more infrastructure and functionality would be needed.

**Comment by Trefex** [comment]
Hi @will-moore. Yes, I think that would be natural for most users. To just see the default colors, their palette and then a color picker in the "more colors..." part. I understand that it makes more sense to store the custom color with the figure itself rather than across the user, as the figure is self-contained in a JSON if I understood correctly. 

It probably even makes more sense, in case you fill the Palette with colors you don't like, you wouldn't want them to spread over all your figures. Also, with the preview I saw that you can do multiple pages in the next release in the same figure, it might even be less important to save colors throughout.

**Comment by will-moore** [comment]
@Trefex Just merged. See screenshot at https://github.com/will-moore/figure/issues/56.

**Comment by Trefex** [comment]
Beautiful. Thanks :+1:
