### ISSUE TITLE
Exporting multiple pages to PDF will only include the first page

### ISSUE THREAD

**Issue by Sethur** [will-moore/figure#41]
Hi,

first of all: Thank you for this very useful plugin, it's one of the things our users like most about working with OMERO.

Now the bug report: Exporting multiple pages to PDF at our system with the latest OMERO.figure from GIT (2012-12-15) will only include the first page. Is this only us or is this functionality missing?

As a side node: The ability to add a label to the scale bar is quire crucial for our users to really adopt the plugin.

Thanks,

Tris

**Comment by will-moore** [comment]
I just pushed an updated PDF export script and some changes to the js app that should handle export of multiple pages on branch: https://github.com/will-moore/figure/tree/multiple_pages
Hasn't been fully tested yet, but you're welcome to give it a try.

**Comment by will-moore** [comment]
NB: Start with a single page figure and update to multiple pages.

**Comment by will-moore** [comment]
This should be fixed now that https://github.com/will-moore/figure/pull/42 is merged. Closing...

**Comment by will-moore** [comment]
The scalebar label issue is addressed by PRs #44 and #45
