### ISSUE TITLE
Scalebar not showing

### ISSUE THREAD

**Issue by will-moore** [will-moore/figure#85]
See figure 33236 on demo server.

20th May: "There seems to be a bug with the scale bar in OMERO.figure (everything else is working OK). When I click "Show" the web page reloads, and no scale bar appears, although the "Show" button is replaced with "Hide". What's odd is that this feature was working correctly when I demo'd it for my group ~3 weeks ago, before the upgrade."

21st May: Screenshots showing that on click of "Show", the "Leave page?" dialog box is shown. If click 'Leave Page' then the "Hide" button is shown for this panel after reload.

Urls update like:
```
.../file/33236
.../file/33236/
.../file/33236/?
```

**Comment by feldman4** [comment]
This is working for me now on the updated server.
